### ISSUE TITLE
USER STORY: Searching for bikes

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/dirtaddictmotors#12]
As a **SiteUser** I can **search for a specific bike** so that **I can quickly see if the bike is available that I am intresting**.

Acceptance Criteria:
- The user should be able to type in the query of their search
- Once the search is made the result should be shown or related to the query
- There should me a message for it there are no search result so the query

Tasks:
- [ ] Create an input field that will hold the query for the search 
- [ ] Have the input field in a form so it can use the GET method
- [ ] Create logic that will show the result of the search
- [ ] Create logic that will show no search result
- [ ] implement logic that takes in to account of searching with no value in the input
