### ISSUE TITLE
USER STORY: 

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/dirtaddictmotors#13]
As a **SiteUser** I can **be able to view a selection of bikes at instance** so that **I can see different types of bikes that are provided in the website**

Acceptance Criteria:
- Have a container that can hold bike items
- Have the user be able to scroll through the container to see all the bikes
- Have the required information for each bike and make minimal information not too detailed
- Have a clickable link that will show even more detailed information about the bike

Story Tasks:
- [ ] Have logic that will get random bikes from my modal. 
- [ ] Cap the limit of bikes to 9
- [ ] Have a container that will hold the bike objects
- [ ] Implement JavaScript to display 3 bikes per slide
- [ ] Implement JavaScript to scroll through the container of bikes with buttona
- [ ] Implement JavaScript to have a timer on the container that will manual change the slides
- [ ] Add links for each bike to display more information of the bike
