### ISSUE TITLE
USER STORY: Have a sort filter for certain criteria

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/dirtaddictmotors#14]
As a **SiteUser** I can **Sort information of the bikes** so that **bikes can be filtered by ascending and decending order for cost, year, and A-z**

Acceptance Criteria:
-Create link's that will display information on a certain field ie Cost, Year and A-Z
- Have the options in the product view for the filtering
- Have a pre-defined sort option on the link so that when the link is clicked it will always show the ascending first.
- Give the option in the product view to descend the information

Story Tasks:
- [ ] Create link's in a dropdown menu that will display the sort option
- [ ] Create an option box in the product view with sort options
- [ ] Create logic that will change the sort order of the given field
- [ ] Create logic that insures that the correct sort fields to given to each filter
