### ISSUE TITLE
USER STORY: Create a view for the product page

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/dirtaddictmotors#15]
As a **SiteUser** I can **look at all the bikes that the site has** so that **I can see the arity of selection of bikes**

Acceptance Criteria:
- Have a page that will display all the bikes
- Give each bike a product card to give the most relevant information that the consumer would need
- Structure the bike in a viewable format with pagination for screen sizes

Story Tasks:
- [ ] Create a page that will hold all the bikes on the website
- [ ] Add CSS to the page so that the page is bland
- [ ] Add structure to the page to the items can be displayed on all screen sizes
- [ ] Create a link on the page so that the item can be viewed individual
- [ ] Create a link that will add the bike to the bag
