### ISSUE TITLE
USER STORY: 

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/dirtaddictmotors#16]
As a **SiteUser** I can **View the individual bike object** so that **I can see me more detailed information on the bike**

Acceptance Criteria:
- Have a page that will hold the information of the individual bike object
- Have the page be displayable in terms of styling and structure
- Have a link that can add the bike to the bag
- Have the option to increase the quantity of the bike
- Have the image of the bike enlarged for a better view of the bike

Story Tasks:
- [ ] Create a page that will display the individual bike object
- [ ] Display all the information about the bike for the user
- [ ] Add a quantity counter for the number of bikes the user want to add to the bag
- [ ] Add a link that will add the bike to the bag
- [ ] Crete the a view for the image to display bigger
