### ISSUE TITLE
USER STORY: Have a view that will dispaly bag

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/dirtaddictmotors#17]
As a **SiteUser** I can **view my bag** so that **I can see my items in my bag**

Acceptance Criteria:
- Have a page that will display the bag
- Have a link that is present on all pages so the bag can be accessed at anytime
- Have an indicator of the number of items in the bag in the link
- Display the items of the bag in a styled and structured fashion
- Display the price, quantity, delivery cost, and total cost of the order
- Have a button that will checkout the order 

Story Tasks:
- [x] Create the page for the bag
- [x] Create a link that can access the bag
- [x] Create logic that will display the number of items in the bag on all pages
- [x] Create a link that will bring these to checkout his bag
- [x] Style and structure the page for all mobile sizes
- [x] Display all the relevant information about the bag variables that are needed
