### ISSUE TITLE
USER STORY: Adjusting the quanity in the bag

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/dirtaddictmotors#18]
As a **SiteUser** I can **change the quantity of each item in the bag** so that **I don't have to go back to the individual product page to do it**

Acceptance Criteria:
- Have a quantity counter for each item in the bag
- Have it display the correct item when first added
- Have buttons that will increase and decrease the value of the quantity
- Have a button that will update the quantity

Story Tasks:
- [ ] Create a button for increasing and decreasing button 
- [ ] Implement JavaScript to handle the button taking in the value of change
- [ ] Create a form for the quantity to POST the data.
- [ ] Create logic that reflects the changes of the quantity to other fields ie price of all items, grand total.
