### ISSUE TITLE
USER STORY: Update the engine capcaity of te bike in the bag

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/dirtaddictmotors#19]
As a **Site User** I can **change the engine capacity of the bike to another capacity** so that **I can quickly adjust the bag rather than removing the item to add another item one again**

Acceptance Criteria:
- Have all the engine capacities for a given model be displayed
- Have the user be able to change the capacity and then have it update
- When updated have the relevant information be displayed with the new values of other variables
- Remove a bike if the given bike is updated to the same value as another bike in the bag and also add to the quantity of the back it has been updated to

Story Tasks:
- [ ] Create logic that will display the correct engine capacities of a bike by model of the bike
- [ ] Have the values in an option box that can be updated using a form with the POST method
- [ ] Create logic that will handle the removal of bikes if that bike capacity does not exist in anymore in the bag
- [ ] Create logic that will handle the quantity being updated if more than one bike is in the bag and have been updated to another to change the quantity of the bike to the new value
- [ ] Create logic that will update variable for price, grand total and item total
