### ISSUE TITLE
USER STORY: Creating an account 

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/dirtaddictmotors#21]
As a **SiteUser** I can **create an account for the site** so that **I can make purchases from the site**

Acceptance Criteria:
- Hava link that will bring the user to a registration form
- Have a form that the user will fill out with the required information
- Have a confirmation email for the account 

Story Tasks:
- [ ] Create a link that will show the registration form
- [ ] Create a form that will have the fields for input ie username, email address, password, and confirm password
- [ ] Create logic that will send the email for confirmation of the account
