### ISSUE TITLE
USER STORY: Sign into account

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/dirtaddictmotors#22]
As a **SiteUser** I can **sign into my personal account** so that ** I can view the detail of my account and make edits to the information**

Acceptance Criteria:
- Have a link for a sign-in that is present on all pages
- Have a form that will require the user to log information for sign in
- Redirect the user to the home page after signing in

Story Tasks:
- [ ] Create a link in the main nav bar for signing in
- [ ] Create the form that will require the information for signing
- [ ] Create logic for validation of the information
- [ ] Create logic that will redirect the user to the home page after a successful sign in
