### ISSUE TITLE
USER STORY: Sign out of my account

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/dirtaddictmotors#23]
As a **SiteUser** I can **sign out of my account** so that **I am not logged in to my account anymore**

Acceptance Criteria:
- Have a link that logs the user out of their account on all pages
- Once logged out the user should be redirect to the sign in page

Story Tasks:
- [ ] Create a link that shows the sign-out link in the main-nav bar
- [ ] Create logic that shows the sign out link only when the user is signed in
- [ ] Create logic that redirects the user to the sign-in page
