### ISSUE TITLE
USER STORY: View your order at checkout

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/dirtaddictmotors#24]
As a **SiteUser** I can **view my order before checkout** so that **see I am happy with my purchase**

Acceptance Criteria:
- Create a page that will display my order detail
- Have the correct information for each item in the order

Story Tasks:
- [ ] Create a page where the user will be redirected from the bag to the checkout page
- [ ] Create logic for all the items from the bag session to be shown on the checkout page.
- [ ] Create logic so that the order shows the subtotal for items, the total cost for all items, the delivery total, and the grand total correctly calculated.
