### ISSUE TITLE
USER STORY:Enter payment detail

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/dirtaddictmotors#29]
As a **site user** I can **enter my payment details ** so that **so that I can purchase my order**

Acceptance Criteria:
- Have a form that will allow the user to enter their payment details 
- Have errors show if the data is invalid
- Have the form be able to process 

Story Tasks:
- [ ] Create a form that will handle the input of payment data
- [ ] Create a button that will submit the payment detail
- [ ] Create logic that will validate the data
