### ISSUE TITLE
USER STORY: Cheackout success page 

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/dirtaddictmotors#30]
As a **SiteUser** I can **be redirected to the checkout success page** so that **know if my order was successful checkout**

Acceptance Criteria:
- Have a page that will bring the user to if the checkout was successful
- Have the detail of the order on the page
- Inform the user that the order is being processed and send an email for confirmation 

Story Tasks:
- [ ] Create a page that will be the checkout success page
- [ ] Create the content on the page including the delivery information, the user information, and the item details
- [ ] Create logic that will send the user a confirmation email that their order is being processed
