### ISSUE TITLE
USER STORY: Add bikes to the website

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/dirtaddictmotors#32]
As a **Site Admin** I can **add more bikes to the website** so that **I can keep adding stock to the website**

Acceptance Criteria:
- Have a form that can be filled out to submit the bikes to the website
- Have a way to submit the form 
- Have it so the Site admin can only add bikes

Story Tasks:
- [ ] Create a form so that the site admin can add bikes to the website 
- [ ] Create a way for the bike be saved
- [ ] Create logic so that the admin only has access to the function
