### ISSUE TITLE
USER STORY: Edit bikes on the website

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/dirtaddictmotors#33]
As a **Site Admin** I can **edit bikes on the website** so that **I can remove bikes that the store does not sell anymore**

Acceptance Criteria:
- Have a form that will access the information about a bike already in the store
- Have the option to make edit to the bike 
- Have the edit's be saved

Story Tasks:
- [ ] Create logic that will allow the site admin to be able to edit bikes on the website
- [ ] Create logic so that the site admin only has access to editing bikes
- [ ] Created logic that the edit bike can be saved
