### ISSUE TITLE
USER STORY: Admin area

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/dirtaddictmotors#39]
As a **Admin** I can ** view all the orders on the website** so that ** update the status of the orders if they are complete**

Acceptance Criteria:
- Have an area where the admin will be able to view the orders on the website
- Have the ability to update the order on status of complete

Story Tasks:
- [x] Create a page that the admin will only be access the admin 
- [x] Have logic that shows all the orders of the store
- [x] Create logic that the admin will be able to update the status of the order
